### ISSUE TITLE
Error when using allOf

### ISSUE THREAD

**Issue by ozum** [tlivings/enjoi#53]
Hi,

**enjoi 3.2.4**

I got following error when using `allOf`:

```
ssertionError [ERR_ASSERTION]: Expected allOf item to be an array or object.
    at new AssertionError (internal/assert.js:268:11)
    at Object.exports.assert (.../node_modules/hoek/lib/index.js:736:11)
    at .../node_modules/enjoi/lib/enjoi.js:187:18
    at Array.map (<anonymous>)
    at resolveAllOf (.../node_modules/enjoi/lib/enjoi.js:185:23)
    at resolve (.../node_modules/enjoi/lib/enjoi.js:38:20)
    at enjoi (.../node_modules/enjoi/lib/enjoi.js:410:12)
    at Object.<anonymous> (.../deneme.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

Here is a minimal sample code: (I tested JsonSchema with a Json Validator and it works as expected)

```js
const Enjoi = require("enjoi");

const schema = Enjoi({
  title: "Organization Input",
  allOf: [
    {
      title: "Organization Common",
      allOf: [
        {
          type: "object",
          properties: {
            name: { type: "string", maxLength: 40 },
            billingAddress: { type: "string", maxLength: 100 }
          },
          required: ["name"]
        },
        {
          type: "object",
          title: "Phone Number",
          properties: { phoneCountryCode: { type: "string", minLength: 1 } },
          required: ["phoneCountryCode"]
        }
      ]
    }
  ]
});
```

Kind regards,

**Comment by ozum** [comment]
Thanks
